version: "3"

services:

    api:
        build:
            context: .
            dockerfile: Dockerfile.api
        restart: always
        container_name: api
        depends_on:
            - postgres
        ports:
            - 8000:8000
        env_file:
            - ./.env
        command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
        volumes:
            - ./:/usr/src/app

    postgres:
        image: postgres
        restart: always
        command: postgres -c 'max_connections=2500'
        container_name: db
        env_file:
            - ./.env
        ports:
            - 5432:5432
        volumes:
            - postgres-db:/var/lib/postgresql/data

    

    coinbase_data_feeder:
        build:
            context: ./app/coinbase_data_feeder
            dockerfile: ./Dockerfile.coinbase
        depends_on:
            - postgres
        restart: always
        container_name: coinbase_data_feeder
        env_file:
            - ./.env
        volumes:
            - ./coinbase_data_feeder:/coinbase_data_feeder

volumes:
    postgres-db:
